version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/docker/nginx_manager/data:/data
      - /home/docker/nginx_manager/letsencrypt:/etc/letsencrypt

networks:
    default:
        name: server_internal
        external: true
