version: "2.1"
services:
  pwndrop:
    image: lscr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=america/chicago
      - SECRET_PATH=/secretsshouldnotbetold #optional
    volumes:
      - /home/docker/pwndrop:/config
    ports:
      - 8080:8080
    restart: unless-stopped

networks:
    default:
        name: network
        external: true
