# Use root/example as user/password credentials
version: '3.1'

services:
  db:
  # port 3306
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example

networks:
    default:
        name: server_internal
        external: true
